/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho;

import Classes.Cargo;
import Classes.Funcionario;
import Classes.SimpleTableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author Joao
 */
public class FormFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form FormFuncionario
     */
    public FormFuncionario() {
        initComponents();
    }

    ArrayList<Funcionario> listaFuncionario = new ArrayList<>();
    ArrayList<Cargo> listaCargo = new ArrayList<>();
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        funcionario_codigo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        funcionario_nome = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        funcionario_cpf = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        funcionario_rg = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        funcionario_email = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        funcionario_ativo = new javax.swing.JCheckBox();
        funcionario_inativo = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        funcionario_dataNasc = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        funcionario_naturalidade = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        funcionario_dataAdmissao = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        funcionario_salvar = new javax.swing.JButton();
        funcionario_editar = new javax.swing.JButton();
        funcionario_excluir = new javax.swing.JButton();
        funcionario_cargo = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jt_funcionario = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        funcionario_vale_trans = new javax.swing.JCheckBox();
        funcionario_vale_refe = new javax.swing.JCheckBox();
        funcionario_aux_edu = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        funcionario_descricao = new javax.swing.JTextField();
        funcionario_plano_saude = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Funcionário");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel19.setText("Código:");

        jLabel20.setText("Nome:");

        jLabel21.setText("CPF:");

        jLabel22.setText("RG:");

        jLabel23.setText("E-mail:");

        jLabel24.setText("Situação:");

        funcionario_ativo.setText("Ativo");

        funcionario_inativo.setText("Inativo");

        jLabel25.setText("Data Nasc:");

        jLabel26.setText("Naturalidade:");

        jLabel28.setText("Data Admissão:");

        jLabel29.setText("Cargo:");

        funcionario_salvar.setText("Salvar");
        funcionario_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionario_salvarActionPerformed(evt);
            }
        });

        funcionario_editar.setText("Editar");

        funcionario_excluir.setText("Excluir");

        funcionario_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jt_funcionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "CPF", "RG", "Cargo", "Data admissão", "Naturalidade", "Data Nasc", "Benefício", "Descrição", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jt_funcionario);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        funcionario_vale_trans.setText("Vale Transporte");

        funcionario_vale_refe.setText("Vale Refeição");

        funcionario_aux_edu.setText("Auxilio Educação");

        jCheckBox4.setText("Outros");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Descrição:");

        funcionario_plano_saude.setText("Plano de Saúde");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(funcionario_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(funcionario_plano_saude)
                    .addComponent(jCheckBox4)
                    .addComponent(funcionario_aux_edu)
                    .addComponent(funcionario_vale_trans)
                    .addComponent(funcionario_vale_refe))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(funcionario_vale_trans)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(funcionario_vale_refe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(funcionario_aux_edu)
                .addGap(5, 5, 5)
                .addComponent(funcionario_plano_saude)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(funcionario_descricao, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(funcionario_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(funcionario_editar)
                        .addGap(18, 18, 18)
                        .addComponent(funcionario_excluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(funcionario_email, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(funcionario_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(funcionario_nome)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(funcionario_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(funcionario_rg, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                            .addComponent(funcionario_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(funcionario_ativo)
                                .addGap(26, 26, 26)
                                .addComponent(funcionario_inativo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(funcionario_dataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(funcionario_naturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(funcionario_dataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(funcionario_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(funcionario_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(funcionario_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22)
                                .addComponent(funcionario_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(funcionario_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(funcionario_ativo)
                            .addComponent(funcionario_inativo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(funcionario_dataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(funcionario_naturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funcionario_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel28)
                    .addComponent(funcionario_dataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funcionario_salvar)
                    .addComponent(funcionario_editar)
                    .addComponent(funcionario_excluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void funcionario_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionario_salvarActionPerformed
        Funcionario funcionario = new Funcionario();
        String nome = funcionario_nome.getText();
        String cpf = funcionario_cpf.getText();
        String naturalidade = funcionario_naturalidade.getText();
        int cargo = 0;
        String cargoNome = funcionario_cargo.getSelectedItem().toString();
        Boolean ativo = funcionario_ativo.isSelected();
        Boolean inativo = funcionario_inativo.isSelected();
        Boolean vale_trans = funcionario_vale_trans.isSelected();
        Boolean vale_refe = funcionario_vale_refe.isSelected();
        Boolean aux_edu = funcionario_aux_edu.isSelected();
        Boolean plano_saude = funcionario_plano_saude.isSelected();
        int codigo =    0;
        String email = funcionario_email.getText();
        String rg = funcionario_rg.getText();
        String descricao = funcionario_descricao.getText();
        String data_admis = funcionario_dataAdmissao.getText();
        
        for (int i = 0; i < listaCargo.size(); i++) {
            
            if( listaCargo.get(i).getCargo().equalsIgnoreCase( cargoNome ) ){
                cargo = listaCargo.get(i).getIdCargo();
            }
            
        }

        funcionario.setNome(nome);
        funcionario.setCpf(cpf);
        funcionario.setCargo(cargo);
        funcionario.setCodigo(codigo);
        funcionario.setRg(rg);
        funcionario.setDescricao(descricao);
        funcionario.setDataAdmissao(data_admis);
        funcionario.setNaturalidade(naturalidade);
        funcionario.setAtivo(ativo);
        funcionario.setInativo(inativo);
        funcionario.setVale_trans(vale_trans);
        funcionario.setVale_refe(vale_refe);
        funcionario.setAux_edu(aux_edu);
        funcionario.setPlano_saude(plano_saude);
      
        try {
            funcionario.cadastrarFuncionario();
        } catch (SQLException ex) {
            Logger.getLogger(FormFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_funcionario_salvarActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        atualizaTabelaFuncionario();
        Cargo cargo = new Cargo();
        
        try {
            listaCargo = cargo.listarCargos();
            
            for (int i = 0; i < listaCargo.size(); i++) {
                funcionario_cargo.addItem( listaCargo.get(i).getCargo() );
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(FormFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowActivated

    public void atualizaTabelaFuncionario(){
        Funcionario funcionario = new Funcionario();
        
        try {
            listaFuncionario = funcionario.listarFuncionario();
            
            jt_funcionario = createJtableFuncionario( listaFuncionario );
            jScrollPane6.setViewportView(jt_funcionario);
            
        } catch (SQLException ex) {
            Logger.getLogger(CadFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public JTable createJtableFuncionario( ArrayList<Funcionario> listafFuncionarios){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[] 
        { "Codigo", "nome","cpf", "rg", "dataNasc", "naturalidade", "email", "dataAdmissao" , "descricao"};
         
        for (Funcionario f:listaFuncionario){
            dados.add(new String[]
            {
                f.getCodigo()+"", f.getNome(), f.getCpf(), f.getRg(), f.getDataNasc(), f.getNaturalidade(), f.getEmail(), f.getDataAdmissao(), f.getDescricao()
            });
        }
        
         SimpleTableModel modelo =
                new SimpleTableModel(dados, colunas);
         
         JTable jtable = new JTable((TableModel) modelo);
         return jtable;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox funcionario_ativo;
    private javax.swing.JCheckBox funcionario_aux_edu;
    private javax.swing.JComboBox<String> funcionario_cargo;
    private javax.swing.JTextField funcionario_codigo;
    private javax.swing.JTextField funcionario_cpf;
    private javax.swing.JTextField funcionario_dataAdmissao;
    private javax.swing.JTextField funcionario_dataNasc;
    private javax.swing.JTextField funcionario_descricao;
    private javax.swing.JButton funcionario_editar;
    private javax.swing.JTextField funcionario_email;
    private javax.swing.JButton funcionario_excluir;
    private javax.swing.JCheckBox funcionario_inativo;
    private javax.swing.JTextField funcionario_naturalidade;
    private javax.swing.JTextField funcionario_nome;
    private javax.swing.JCheckBox funcionario_plano_saude;
    private javax.swing.JTextField funcionario_rg;
    private javax.swing.JButton funcionario_salvar;
    private javax.swing.JCheckBox funcionario_vale_refe;
    private javax.swing.JCheckBox funcionario_vale_trans;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jt_funcionario;
    // End of variables declaration//GEN-END:variables
}
