/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho;

import Classes.Agenda;
import Classes.Funcionario;
import Classes.SimpleTableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static trabalho.Relatorio.agenda;
import static trabalho.Relatorio.pesquisa;

/**
 *
 * @author Yuri
 */
public class Relatorio extends javax.swing.JFrame {

    /**
     * Creates new form Relatorio
     */
    public Relatorio() {
        initComponents();
    }
    ArrayList<Agenda> listaAgenda = new ArrayList<Agenda>();
    static Agenda agenda = new Agenda();
    Funcionario funcionario = new Funcionario();
    static ArrayList<Agenda> pesquisa = new ArrayList();
    static ArrayList<Funcionario> Funcionario = new ArrayList();
    static String carregar = "";
    //retornaPesquisa
    public void setPesquisa(ArrayList<Agenda> listaAgenda){
        pesquisa = listaAgenda;
        carregar = "Agenda";
    }
    public void setFuncionario(ArrayList<Funcionario> listaFuncionario){
        Funcionario = listaFuncionario;
        carregar = "Funcionario";
    }

    public JTable createJtable( ArrayList<Agenda> listaAgenda ){
        JLabel labelSingleClick = new JLabel("Single click me.");
        ArrayList dados = new ArrayList();
        String[] colunas = new String[] 
        {"ID","Nome","Titulo", "Prioridade", "Data", "Hora"};


        for (Integer i = 0; i < pesquisa.size(); i++){
           dados.add(new String[]
            {pesquisa.get(i).getIdAgenda(), pesquisa.get(i).getNomeFuncionario(), pesquisa.get(i).getTitulo(), pesquisa.get(i).getPrioridade(), pesquisa.get(i).getData(), pesquisa.get(i).getHora(),}
           );
        }

        SimpleTableModel modelo =
            new SimpleTableModel(dados, colunas);

        JTable jtable = new JTable(modelo);
        return jtable;
    }
    public JTable createJtableFuncionario( ArrayList<Funcionario> listaFuncionario ){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[] 
        {"ID","Nome","CPF", "RG", "Naturalidade","Data Nasc.","Data Admissão","Cargo","Descricao","Ativo","Inativo","E-mail","Auxilio Educação","Vale Refeição","Plano de Saúde","Vale Transporte","Outros"};
        

        for (Integer i = 0; i < Funcionario.size(); i++){
           dados.add(new String[]
            {Integer.toString(Funcionario.get(i).getCodigo()),
            Funcionario.get(i).getNome(),
            Funcionario.get(i).getCpf(),
            Funcionario.get(i).getRg(),
            Funcionario.get(i).getNaturalidade(),
            Funcionario.get(i).getDataNasc(),
            Funcionario.get(i).getDataAdmissao(),
            Integer.toString(Funcionario.get(i).getCargo()),
            Funcionario.get(i).getDescricao(),
            Integer.toString(Funcionario.get(i).isAtivo()),
            Integer.toString(Funcionario.get(i).isInativo()),
            Funcionario.get(i).getEmail(),
            Integer.toString(Funcionario.get(i).isAux_edu()),
            Integer.toString(Funcionario.get(i).isVale_refe()),
            Integer.toString(Funcionario.get(i).isPlano_saude()),
            Integer.toString(Funcionario.get(i).isVale_trans()),
            Integer.toString(Funcionario.get(i).getOutros())}
           );
        }

        SimpleTableModel modelo =
            new SimpleTableModel(dados, colunas);

        JTable jtable = new JTable(modelo);
        return jtable;
    }
    public void atualizaTabela(){
        //Agenda agenda = new Agenda();
        //listaAgenda = agenda.listarAgenda();
        jtGrid = createJtable( pesquisa );
        jsRel.setViewportView(jtGrid);
    }  
    public void atualizaFuncionario(){
        jtGrid = createJtableFuncionario( Funcionario );
        jsRel.setViewportView(jtGrid);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jsRel = new javax.swing.JScrollPane();
        jtGrid = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jtGrid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Título", "Prioridade", "Data ", "Hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtGrid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtGridMouseClicked(evt);
            }
        });
        jsRel.setViewportView(jtGrid);

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jsRel, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsRel, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if(carregar.equalsIgnoreCase("Agenda")){
            atualizaTabela();
        }
        if(carregar.equalsIgnoreCase("Funcionario")){
            atualizaFuncionario();
        }
    }//GEN-LAST:event_formWindowOpened

    private void jtGridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtGridMouseClicked
    }//GEN-LAST:event_jtGridMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Relatorio.this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane jsRel;
    private javax.swing.JTable jtGrid;
    // End of variables declaration//GEN-END:variables
}
